# Generated by Django 2.2.6 on 2019-10-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='id_proyecto',
            field=models.IntegerField(default=0),
        ),
    ]
