# Generated by Django 2.2.6 on 2019-10-26 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_proyecto_id_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='id_proyecto',
        ),
    ]
