# Generated by Django 3.1.6 on 2021-06-27 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rol', '0001_initial'),
        ('accounts', '0004_user_id_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_rol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Rol.rol'),
        ),
    ]
