# Generated by Django 2.2.6 on 2019-11-01 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineaBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('fase', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'LineaBase',
                'verbose_name_plural': 'LineasBase',
            },
        ),
    ]
