# Generated by Django 2.2.4 on 2019-11-01 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_auto_20191029_1237'),
        ('LineaBase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineabase',
            name='id_proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.Proyecto'),
        ),
    ]
