# Generated by Django 2.2.6 on 2019-11-04 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LineaBase', '0002_lineabase_id_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineabase',
            name='id_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyecto'),
        ),
    ]
