# Generated by Django 2.2.6 on 2019-11-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LineaBase', '0003_auto_20191103_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineabase',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
