# Generated by Django 2.2.6 on 2019-11-04 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id_lb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LineaBase.LineaBase'),
        ),
    ]
