# Generated by Django 3.1.6 on 2021-02-19 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Roles.rol')),
            ],
        ),
    ]
