# Generated by Django 3.1.6 on 2021-04-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('prioridad', models.CharField(choices=[('Alta', 'Alta'), ('Baja', 'Baja'), ('Normal', 'Normal')], max_length=10)),
                ('estado', models.CharField(choices=[('Iniciado', 'Iniciado'), ('Pendiente', 'Pendiente'), ('Finalizado', 'Finalizado')], max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('observacion', models.CharField(max_length=100)),
                ('id_tarea_padre', models.IntegerField(null=True)),
            ],
        ),
    ]
