# Generated by Django 3.1.6 on 2021-02-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='id',
        ),
        migrations.AddField(
            model_name='rol',
            name='id_rol',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
